[tools]
"devbox:rcs" = "latest"
"devbox:exiftool" = "latest"
"devbox:htop" = "latest"
"devbox:taskwarrior-tui" = "latest"
"devbox:taskwarrior" = "latest"
"devbox:timewarrior" = "latest"
"devbox:gpg-tui" = "latest"
"devbox:renameutils" = "latest"
"devbox:poppler-utils" = "latest"
"devbox:git-extras" = "latest"
"devbox:git" = "latest"
"devbox:gawk" = "latest"
"devbox:file" = "latest"
