[tools]
"aqua:ip7z/7zip" = "latest"
"cargo:findutils" = "latest"
hyperfine = "latest"
tssh = "latest"
"cargo:aws/amazon-q-developer-cli" = { version = "tag:v1.19.6", crate = "chat_cli" }
ffmpeg = "latest"
numbat = "latest"
"github:mat2cc/redis_tui" = "latest"
claude = "latest"
